/// Flutter icons MyFlutterApp
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
///
/// * Maki, Copyright (C) Mapbox, LCC
///         Author:    Mapbox
///         License:   BSD (https://github.com/mapbox/maki/blob/gh-pages/LICENSE.txt)
///         Homepage:  http://mapbox.com/maki/
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const String? _kFontPkg = null;

  static const IconData swimming =
      IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pills =
      IconData(0xea61, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}

class HearthIcon {
  HearthIcon._();

  static const _kFontFam = 'HearthIcon';
  static const String? _kFontPkg = null;

  static const IconData handHoldingHeart =
      IconData(0xf4be, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}

class PilIcon {
  PilIcon._();

  static const _kFontFam = 'PilIcon';
  static const String? _kFontPkg = null;

  static const IconData pills =
      IconData(0xea61, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
