// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv9T4XwQ9mykECKI5Xgiozud637kTpkJg',
    appId: '1:641475881348:web:4177ee7b0a44c25617d5d1',
    messagingSenderId: '641475881348',
    projectId: 'toturu-a6162',
    authDomain: 'toturu-a6162.firebaseapp.com',
    storageBucket: 'toturu-a6162.appspot.com',
    measurementId: 'G-80GW2NH59L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZu794M7QKabLc2rckplvx899Kg5CsJDw',
    appId: '1:641475881348:android:461edefb671b9c6917d5d1',
    messagingSenderId: '641475881348',
    projectId: 'toturu-a6162',
    storageBucket: 'toturu-a6162.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvOwn3TydCOK2TV9pFHx-c3Y4Sth8njaQ',
    appId: '1:641475881348:ios:ddd5c253b2ee94c017d5d1',
    messagingSenderId: '641475881348',
    projectId: 'toturu-a6162',
    storageBucket: 'toturu-a6162.appspot.com',
    iosClientId: '641475881348-8eqbsi76splo35j7br71p3j43sqa2grj.apps.googleusercontent.com',
    iosBundleId: 'com.example.toturo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvOwn3TydCOK2TV9pFHx-c3Y4Sth8njaQ',
    appId: '1:641475881348:ios:ddd5c253b2ee94c017d5d1',
    messagingSenderId: '641475881348',
    projectId: 'toturu-a6162',
    storageBucket: 'toturu-a6162.appspot.com',
    iosClientId: '641475881348-8eqbsi76splo35j7br71p3j43sqa2grj.apps.googleusercontent.com',
    iosBundleId: 'com.example.toturo',
  );
}
